### ISSUE TITLE
1 << 11

### ISSUE THREAD

**Issue by LewisTehMinerz** [LewisTehMinerz/discord-flags#1]
1 << 11 is currently the only flag missing from our list that we know about. Some say it was a reserved flag that was never used, some say it's a mysterious flag that will lead to your death<sup>1</sup>!

<sup>1: no one said this</sup>

Anyway, it would be great if we could document whatever this mystery flag is. Someone already datamined the Discord client and didn't find anything regarding it. Maybe someone else can find it? I don't know. Maybe I missed something.

**Comment by LewisTehMinerz** [comment]
User ID `562415519454461962` has ONE_ELEVEN as a user flag. We now know it's used, just that we don't know what for.

**Comment by LewisTehMinerz** [comment]
[Made a document detailing some stuff](https://docs.google.com/document/d/1tsxcNxhSlbHjAyQHhHJj2koGEzzsl5WFkNb8YMHZIR8/edit?usp=sharing).

**Comment by BannerBomb** [comment]
My id also has it `269247101697916939`

**Comment by MeguminSama** [comment]
More information on the flag is provided in this issue here https://github.com/discord/discord-api-docs/issues/1823

**Comment by LewisTehMinerz** [comment]
It's an internal flag.

Anyway, the hunt is over. We know it's related to partner/verification applications and it was accidentally leaked to clients' private flags. We'll give it a name and description soon.
