### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mrhappyma** [LewisTehMinerz/discord-flags#10]
Hello!

I was filling out the "capture the flag" form and came upon the "i have verified my phone number" checkbox. I have verified it before, but i removed it from my account about 2 weeks after and it is not currently linked. Should I check that box?

**Comment by MeguminSama** [comment]
Since you removed it, leave it unchecked.

**Comment by mrhappyma** [comment]
> Since you removed it, leave it unchecked.

ok, ty
