### ISSUE TITLE
DISABLED (1 << 41)

### ISSUE THREAD

**Issue by apos37** [LewisTehMinerz/discord-flags#12]
## Flag Name
DISABLED (1 << 41)

## Flag Description
User is currently temporarily or permanently disabled.

## Extra Info
- [ X ] Flag is documented
- [ X ] I got this flag from this source: https://flags.lewistehminerz.dev/

## My Notes
I wrote a script for a Discord bot to return all users and their publicFlags. Several people in a couple of servers I'm in have this flag, and yet they are currently active and not disabled. This must be incorrect.

**Comment by aiko-chan-ai** [comment]
@apos37  can you tell me some Ids that you have tested

**Comment by apos37** [comment]
@aiko-chan-ai , do you have an email that I can send them to? I'd rather not make user ids public.

**Comment by apos37** [comment]
Actually, I found your discord name on your profile and sent you a friend request. My discord is Aristocles.

**Comment by aiko-chan-ai** [comment]
> @aiko-chan-ai , I found your discord name on your profile and sent you a friend request. My discord is Aristocles. I can send you the ids there so they are not public.

please send them to me, i will check them the next day
maybe it will be the same error I got

**Comment by apos37** [comment]
@Vordlex , it says you're not accepting friend requests. Please send one to me: Aristocles#6412

**Comment by aiko-chan-ai** [comment]
> @aiko-chan-ai , I will, but you need to accept my friend request in order to accept messages from me.
> 
> @Vordlex , yes

I don't turn off direct message
![Screenshot_20220708-023436](https://user-images.githubusercontent.com/71698422/177857494-0e7109d5-8e8a-4465-ae20-7da23e441d30.jpg)

**Comment by apos37** [comment]
@Vordlex 
![image](https://user-images.githubusercontent.com/58490438/177858075-33a07d9a-06ac-4142-bf6f-74f4f70ad799.png)
