### ISSUE TITLE
Mixed user and application flags

### ISSUE THREAD

**Issue by ShockTr** [LewisTehMinerz/discord-flags#14]
1 << 23 (APPLICATION_COMMAND_BADGE) that got introduced in #13 is an Application flag unlike the all the other flags that are contained in this repo which are User flags

**Comment by ShockTr** [comment]
> I think we can make an exemption for this since it applies to the bot account's profile, no?

It doesn't apply to bot user, it only applies to the application itself

**Comment by LewisTehMinerz** [comment]
hmm, so we need to differentiate then, mkay

**Comment by LewisTehMinerz** [comment]
flags have been split
`flags.json -> /flags/user.json`
`/flags/application.json`
