### ISSUE TITLE
1 << 18 (CERTIFIED_MODERATOR)

### ISSUE THREAD

**Issue by Cynosphere** [LewisTehMinerz/discord-flags#3]
## Flag Name
CERTIFIED_MODERATOR

## Flag Description
Discord Certified Moderator

## Extra Info
- [x] Flag is documented
- [x] I got this flag from this source: https://discord.com/developers/docs/resources/user#user-object-user-flags

**Comment by LewisTehMinerz** [comment]
Added in 8a5e167, thank you.
